version: '3.8'

services:
  web2:
    image: dacperezce/converter_worker:v1
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - media_volume:/home/app/worker/flaskr/media
    expose:
      - 5000
    env_file:
      - ./.env.prod.worker
    depends_on:
      - rabbitmq
  web:    
    image: dacperezce/converter_web:v1
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - media_volume:/home/app/web/flaskr/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - web2
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    env_file:
      - ./.env.prod.amb
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  nginx:
    build: ./services/nginx
    volumes:
      - media_volume:/home/app/web/flaskr/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  media_volume: