version: '3.8'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - media_volume:/home/app/web/flaskr/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    env_file:
      - ./.env.prod.amb
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  nginx:
    build: ./services/nginx
    volumes:
      - media_volume:/home/app/web/flaskr/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  media_volume: