version: '3.8'

services:
  web:    
    image: dacperezce/converter_web:v1
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - /nfs/general:/home/app/web/flaskr/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - web2
  nginx:
    build: ./nginx
    volumes:
      - /nfs/general:/home/app/web/flaskr/media
    ports:
      - 80:80
    depends_on:
      - web