version: '3.8'
services:
  web2:
    image: dacperezce/converter_worker:v1
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - /nfs/general:/home/app/worker/flaskr/media
    ports:
      - 80:5000
    env_file:
      - ./.env.prod.worker
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:latest
    env_file:
      - ./.env.prod.amb
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'