
runtime: custom
service: default
env: flex
env_variables:
  FLASK_APP: flaskr/__init__.py
  FLASK_DEBUG: 0
  DATABASE_URL: postgresql://converter:converter@10.175.224.3:5432/converter_db
  BUCKET: converter_uniandes_24
  PROJECT_ID: uniandes-nube
  TOPIC: converter
  SQL_HOST: 10.175.224.3
  SQL_PORT: 5432
  DATABASE: postgres
manual_scaling:
  instances: 1
network:
  name: converter-internal-app
  instance_tag: lb-backend
  subnetwork_name: subred-c